# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: frame.proto for package 'bicycle'

require 'grpc'
require 'frame_pb'

module Bicycle
  module Frame
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bicycle.Frame'

      rpc :CreateFrame, ::Bicycle::CreateFrameRequest, ::Bicycle::CreateFrameResponse
    end

    Stub = Service.rpc_stub_class
  end
end
