# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("frame.proto", :syntax => :proto3) do
    add_message "bicycle.CreateFrameRequest" do
      optional :manufacturer, :string, 1
      optional :material, :enum, 2, "bicycle.FrameMaterial"
      optional :size, :enum, 3, "bicycle.FrameSize"
      optional :type, :enum, 4, "bicycle.FrameType"
    end
    add_message "bicycle.CreateFrameResponse" do
      optional :frame, :message, 1, "bicycle.BikeFrame"
    end
    add_message "bicycle.BikeFrame" do
      optional :id, :string, 1
      optional :manufacturer, :string, 2
      optional :material, :enum, 3, "bicycle.FrameMaterial"
      optional :size, :enum, 4, "bicycle.FrameSize"
      optional :type, :enum, 5, "bicycle.FrameType"
      optional :part_count, :uint32, 6
    end
    add_enum "bicycle.FrameMaterial" do
      value :FRAME_MATERIAL_UNSPECIFIED, 0
      value :FRAME_MATERIAL_ALUMINUM, 1
      value :FRAME_MATERIAL_STEEL, 2
      value :FRAME_MATERIAL_CARBON, 3
    end
    add_enum "bicycle.FrameSize" do
      value :FRAME_SIZE_UNSPECIFIED, 0
      value :FRAME_SIZE_XXS, 1
      value :FRAME_SIZE_XS, 2
      value :FRAME_SIZE_S, 3
      value :FRAME_SIZE_M, 4
      value :FRAME_SIZE_L, 5
      value :FRAME_SIZE_XL, 6
    end
    add_enum "bicycle.FrameType" do
      value :FRAME_TYPE_UNSPECIFIED, 0
      value :FRAME_TYPE_ROAD, 1
      value :FRAME_TYPE_MOUNTAIN, 2
      value :FRAME_TYPE_BMX, 3
      value :FRAME_TYPE_GRAVEL, 4
    end
  end
end

module Bicycle
  CreateFrameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.CreateFrameRequest").msgclass
  CreateFrameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.CreateFrameResponse").msgclass
  BikeFrame = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.BikeFrame").msgclass
  FrameMaterial = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.FrameMaterial").enummodule
  FrameSize = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.FrameSize").enummodule
  FrameType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("bicycle.FrameType").enummodule
end
